### ISSUE TITLE
Align ontology with its actual use in TermIt and other tools

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/popis-dat-ontology#3]
Originally, the class `pdp:term` was supposed to represent a domain term. So the the popis dat ontology uses it in place of domain and range of several properties.
However, the tools we use now (mainly [TermIt](https://github.com/kbss-cvut/termit)) use SKOS Concept (`skos:Concept`) to represent domain terms. While `pdp:term` is a descendant of `skos:Concept`, the data currently do not correspond to the ontology, because they do not match the domains and ranges using `pdp:term` (it is more specific than the data).
This misalignment should be fixed.

**Comment by MichalMed** [comment]
The proposed solution is to replace usages of pdp:term in popis dat ontology with skos:Concept.

**Comment by MichalMed** [comment]
solved with https://github.com/kbss-cvut/popis-dat-ontology/pull/5
