### ISSUE TITLE
Přidat koncept smazání objektu

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/popis-dat-ontology#8]
V hierarchii změn nám chybí typ "smazání entity". Mělo by se jednat o podtyp změny, stejně jako vytvoření entity a úprava entity.

**Comment by MichalMed** [comment]
https://github.com/kbss-cvut/popis-dat-ontology/commit/5beac1c7a41b4f82b8df7ffd594e1f77e75753b1
